### ISSUE TITLE
doesnt render from in game camera only scene view

### ISSUE THREAD

**Issue by grimtin10** [SanielX/DeferredDecals#1]
i have no idea whats wrong

**Comment by SanielX** [comment]
Yeah this repo is really old
Anyway, you might want to try next thing
In DeferredDecalRenderer.cs
Add following code:
```csharp
void OnEnable()  => Camera.onPreRender += RenderDecals;
void OnDisable() => Camera.onPreRender  -= RenderDecals; 
```

Then change Update() method definition to be `RenderDecals(Camera cam)`
And then remove this line
```
var cam = Camera.current;
```

This should basically make decals render on every camera

**Comment by grimtin10** [comment]
that fixed it! thanks
